---
name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checking out code from GitHub
        uses: actions/checkout@v2.3.4
      - name: Set up Python 3.7
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements_test.txt
          pip install -r requirements.txt
          pip install pre-commit
          pip list
          pre-commit --version
      - name: Run pre-commit on all files
        run: |
          pre-commit run --all-files --show-diff-on-failure
  test:
    name: Python ${{ matrix.python }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest
    needs: [linting]
    strategy:
      matrix:
        os: [ubuntu]
        python: [3.7, 3.8, 3.10]
    steps:
      - name: Checking out code from GitHub
        uses: actions/checkout@v2.3.4
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2.2.2
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements_test.txt
          pip install -r requirements.txt
          pip list
      - name: Pytest with coverage reporting
        run: pytest --cov=sonarr --cov-report=xml
      - name: Upload coverage to Codecov
        if: matrix.python == 3.8 && matrix.os == 'ubuntu'
        uses: codecov/codecov-action@v1.5.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
  docs:
    name: Generate and Upload Documentation
    runs-on: ubuntu-latest
    needs: [test]
    steps:
    - name: Checking out code from GitHub
      uses: actions/checkout@v2.3.4
    - name: Set up Python 3.8
      uses: actions/setup-python@v2.2.2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: python -m pip install --upgrade pip pdoc3
    - name: Generate documentation
      run: pdoc --html unmanic_api
    - name: Deploy Documentation
      uses: JamesIves/github-pages-deploy-action@v4.2.2
        with:
          branch: docs
          folder: html/unmanic_api
