---
name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docs:
    name: Generate and Upload Documentation
    runs-on: ubuntu-latest
    steps:
    - name: Checking out code from GitHub
      uses: actions/checkout@v2.3.4
    - name: Set up Python 3.8
      uses: actions/setup-python@v2.2.2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip pdoc3
        pip install -r requirements.txt
        pip list
    - name: Generate documentation
      run: pdoc --html unmanic_api
    - name: Deploy Documentation
      uses: JamesIves/github-pages-deploy-action@v4.2.2
      with:
        branch: docs
        folder: html/unmanic_api
